INSERT INTO weather (
weather_id,weatherState,disasterSubCategoryRegion1,
prefecturalForecastRegion1,
disasterSubCategoryRegion2,
prefecturalForecastRegion2,
disasterSubCategoryRegion3,
prefecturalForecastRegion3,
disasterSubCategoryRegion4,
prefecturalForecastRegion4)
VALUES();